name: build

on:
    pull_request:
        branches: 
          - '**'
    push:
        branches:
          - 'main'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: sudo apt-get install -y xsltproc
      - run: bun run build
      - run: bun run test
